Update privacy policy
wulkanowy/wulkanowy.github.io pull request #71
Opened 2021-11-16 11:46 UTC by Faierbel

2021-11-16 14:38 UTC, JelNiSlaw requested changes

2021-11-16 14:38 UTC, JelNiSlaw commented on src/views/PrivacyPolicy.vue
> +        odbywa się tylko i&nbsp;wyłącznie po włączeniu reklam w&nbsp;ustawieniach aplikacji i&nbsp;po zakceptowaniu
Brakuje jednego "a" w "zakceptowaniu"

2021-11-16 14:38 UTC, JelNiSlaw commented on src/views/PrivacyPolicy.vue
> +        Polityki Prywatności. Aplikacja po zainstalowaniu lub zaaktualizowaniu, domyślnie bez zgody
O jedno "a" za dużo w "zaaktualizowaniu"

2021-11-16 14:38 UTC, JelNiSlaw commented on src/views/PrivacyPolicy.vue
> +        identyfikatora reklamowego a&nbsp;także nie wyświetla reklam.
Proponuję uprościć to zdanie do "Po zainstalowaniu, aplikacja domyślnie nie zbiera danych w celach reklamowych, nie korzysta z unikalnego identyfikatora reklamowego, ani nie wyświetla reklam bez zgody użytkownika."

2021-11-16 14:38 UTC, JelNiSlaw commented on src/views/PrivacyPolicy.vue
> +        przechowywania nie jest w&nbsp;100% bezpieczna i&nbsp;niezawodna więc nie możemy zagwarantować jej absolutnego bezpieczeństwa.
"transmisji *danych*", "przechowywania *ich*"

2021-11-16 14:38 UTC, JelNiSlaw commented on src/views/PrivacyPolicy.vue
> +        przechowywania nie jest w&nbsp;100% bezpieczna i&nbsp;niezawodna więc nie możemy zagwarantować jej absolutnego bezpieczeństwa.
"nie jest w 100% bezpieczna […] więc nie możemy zagwarantować jej […] bezpieczeństwa"

2021-11-16 14:38 UTC, JelNiSlaw commented on src/views/PrivacyPolicy.vue
> +        Niniejsza polityka obowiązuje od 16.11.2021
Brakuje kropki na końcu zdania po dacie

2021-11-16 14:38 UTC, JelNiSlaw commented on src/views/PrivacyPolicy.vue
> +        Jeśli masz jakiekolwiek pytania lub sugestie dotyczące naszej Polityki Prywatności,
Proponuję "*niniejszej* Polityki Prywatności", aby uniknąć powtórzenia w następnej linii

2021-11-17 10:38 UTC, mklkj approved these changes

2021-11-17 10:39 UTC, merged