Correction of spelling errors in FAQ
wulkanowy/wulkanowy.github.io pull request #73
Opened 2021-11-24 19:25 UTC by Zaptyp

2021-11-29 06:06 UTC, JelNiSlaw requested changes
Ten Pull Request wprowadza więcej błędów, niż naprawia.

2021-11-29 06:06 UTC, JelNiSlaw commented on src/assets/faq-answers/co-to-jest-symbol.md
> +Poprawny dla twojej szkoły symbol znajdziesz po zalogowaniu się do dziennika UONET+ przez przeglądarkę i przejściu
Gratuluję, przez tę zmianę w zdaniu znalazły się dwa spójniki „i”, oraz nie brzmi ono dobrze

2021-11-29 06:06 UTC, JelNiSlaw commented on src/views/PrivacyPolicy.vue
> +        Polityki Prywatności. Po zainstalowaniu aplikacja domyślnie nie zbiera danych w celach reklamowych,
Błąd interpunkcyjny

2021-11-29 06:08 UTC, Zaptyp commented
Ten pan powoduje więcej zamieszania niż ma mózgu

2021-11-29 14:27 UTC, Daxxxis commented on src/views/PrivacyPolicy.vue
> +        Polityki Prywatności. Po zainstalowaniu aplikacja domyślnie nie zbiera danych w celach reklamowych,
Poprzednia wersja była poprawna

2021-11-29 14:31 UTC, Daxxxis requested changes
Zalecałbym zastosowanie się do wymienionych uwag

2022-01-07 16:53 UTC, Daxxxis requested changes

2022-01-07 16:53 UTC, Daxxxis commented on public/index.html
> +      <strong>Przpraszamy, Strona Wulkanowego wymaga włączenia JavaScriptu”</strong>
Zjadłeś "e" w słowie "Przepraszamy". Dlaczego "strona" ma być z wielkiej litery i co to za cudzysłów na końcu?

2022-01-07 16:53 UTC, Daxxxis commented on src/assets/faq-answers/co-to-jest-symbol.md
> -Poprawny dla twojej szkoły symbol znajdziesz po zalogowaniu się do dziennika UONET+ przez przeglądarkę, przejściu
Usunięcie tego przecinka, psuje to zdanie – jest niepoprawne

2022-01-07 16:53 UTC, Daxxxis commented on src/assets/faq-answers/co-to-jest-symbol.md
> +przez kafelek **Uczeń NOWOŚĆ** do zakładki **Dostęp mobilny** i po kliknięciu w **Wygeneruj kod dostępu** (symbol zaznaczony kursorem):
Ta zmiana jest także bez sensu, psuje układ całego zdania.

2022-01-07 16:55 UTC, Zaptyp commented on src/assets/faq-answers/co-to-jest-symbol.md
> +przez kafelek **Uczeń NOWOŚĆ** do zakładki **Dostęp mobilny** i po kliknięciu w **Wygeneruj kod dostępu** (symbol zaznaczony kursorem):
To powiedz mi jak byś ułożył te zdanie bez powtórzeń?

2022-01-07 17:04 UTC, Daxxxis commented on src/assets/faq-answers/co-to-jest-symbol.md
> +przez kafelek **Uczeń NOWOŚĆ** do zakładki **Dostęp mobilny** i po kliknięciu w **Wygeneruj kod dostępu** (symbol zaznaczony kursorem):
Przecież w oryginale nie ma powtórzeń

2022-01-07 17:26 UTC, Daxxxis requested changes

2022-01-07 17:26 UTC, Daxxxis commented on public/index.html
> +      <strong>Przepraszamy, Strona Wulkanowego wymaga włączenia JavaScriptu”</strong>
```suggestion
      <strong>Przepraszamy, strona Wulkanowego wymaga włączenia JavaScriptu</strong>
```

2022-01-07 17:26 UTC, Daxxxis commented on src/assets/faq-answers/co-to-jest-symbol.md
>  Poprawny dla twojej szkoły symbol znajdziesz po zalogowaniu się do dziennika UONET+ przez przeglądarkę, przejściu
```suggestion
Poprawny symbol dla twojej szkoły znajdziesz na stronie dziennika UONET+, po uprzednim zalogowaniu się. Zlokalizujesz go, przechodząc
```

2022-01-07 17:26 UTC, Daxxxis commented on src/assets/faq-answers/co-to-jest-symbol.md
> +przez kafelek **Uczeń NOWOŚĆ** do zakładki **Dostęp mobilny** i po kliknięciu w **Wygeneruj kod dostępu** (symbol zaznaczony kursorem):
```suggestion
przez kafelek **Uczeń NOWOŚĆ** do zakładki **Dostęp mobilny**, po kliknięciu w **Wygeneruj kod dostępu** (symbol został zaznaczony kursorem):
```

2022-01-07 17:31 UTC, Daxxxis approved these changes

2022-02-05 13:50 UTC, maciejla commented on src/assets/faq-answers/czym-roznia-sie-wersje-stabilne-i-dev.md
> +Wszystkie typy wersji DEV można pobrać jedynie z naszej strony internetowej i z naszego serwera Discord.
`jedynie` nie gryzie się trochę z `i`? albo `jedynie z naszej strony internetowej` albo `z naszej strony internetowej i/oraz naszego serwera Discord`, "**jedynie** z naszej strony internetowej **i** z naszego serwera Discord" brzmi trochę dziwnie

2022-02-13 10:53 UTC, mklkj requested changes

2022-02-13 10:53 UTC, mklkj commented on src/assets/faq-answers/co-to-jest-symbol.md
> +przez kafelek **Uczeń NOWOŚĆ** do zakładki **Dostęp mobilny**, po kliknięciu w **Wygeneruj kod dostępu** (symbol został zaznaczony kursorem):
Jak już to zmieniamy to pasuje to zmienić na lepsze. Może zrobić po prostu listę kroków?

2022-02-28 19:16 UTC, mklkj approved these changes

2022-02-28 19:16 UTC, merged